#!/bin/sh

if uname -r | grep -qs "\-server"; then
	echo
	echo "For documentation and useful resources, please visit:"
	echo " * http://ubuntu.com/server/doc"
else
	echo
	echo "For official documentation, please visit:"
	echo " * http://www.blankonlinux.or.id/"
fi
